### ISSUE TITLE
Test results disappear when several runs are initiated in sequence.

### ISSUE THREAD

**Issue by ChristianLieven** [DD-DeCaF/memote-webservice#16]
Please see the attached gif:

https://recordit.co/dufTA0A5VO

I've been able to reproduce this bug with the test model e_coli_core.json on the memote.io website too. 

An associated phenomenon seems to be: Deleting one result will then also delete all results.

Tested and reproduced in Chrome, Safari, and Firefox.

**Comment by kvikshaug** [comment]
Thanks for the detailed report! This was fixed in https://github.com/DD-DeCaF/memote-service-frontend/pull/23 :)
